version: '3.3'

services:
  docker-in-docker:
    image: docker:latest
    container_name: docker-in-docker
    privileged: true  # Required for Docker-in-Docker
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs  # Set TLS_CERT_DIR to a subdirectory
    volumes:
      - ./dind-data:/var/lib/docker  # Persistent Docker data
      - ./certs:/certs  # Mount the certs directory
      - ./dind-post.sh:/post-install.sh  # Mount the post-install script
    ports:
      - "2377:2376"  # Change the host port to 2377
    command: >
      sh -c "
      netstat -tuln | grep 2376      TLS_CERT_DIR='/certs';
      mkdir -p $TLS_CERT_DIR;

      # Fix permissions for mounted directories
      echo '🔧 Fixing permissions for mounted directories...';
      chown -R 1000:1000 /var/lib/docker $TLS_CERT_DIR;
      chmod -R 755 /var/lib/docker $TLS_CERT_DIR;

      # Generate self-signed TLS certificates if missing
      if [ ! -f \"$TLS_CERT_DIR/ca.pem\" ] || [ ! -f \"$TLS_CERT_DIR/server-cert.pem\" ] || [ ! -f \"$TLS_CERT_DIR/server-key.pem\" ]; then
          echo '🔑 Generating self-signed TLS certificates...';
          openssl req -newkey rsa:4096 -nodes -keyout $TLS_CERT_DIR/server-key.pem -x509 -days 365 -out $TLS_CERT_DIR/server-cert.pem -subj '/CN=docker-in-docker';
          cp $TLS_CERT_DIR/server-cert.pem $TLS_CERT_DIR/ca.pem;
      else
          echo '🔑 TLS certificates already exist. Skipping generation.';
      fi;

      # Debug: List certificates
      echo '🔍 Debug: Listing certificates in $TLS_CERT_DIR...';
      ls -l $TLS_CERT_DIR;

      # Start Docker daemon with a custom Unix socket
      echo '🔒 Starting Docker daemon...';
      dockerd --debug --host=tcp://0.0.0.0:2376 --host=unix:///var/run/docker-dind.sock --storage-driver=overlay2 --tlsverify --tlscacert=$TLS_CERT_DIR/ca.pem --tlscert=$TLS_CERT_DIR/server-cert.pem --tlskey=$TLS_CERT_DIR/server-key.pem;

      sleep 5;
      sh /post-install.sh"
volumes:
  dind-data: