version: '3.3'

services:
  docker-in-docker:
    image: docker:latest
    container_name: docker-in-docker
    privileged: true  # Required for Docker-in-Docker
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - DOCKER_TLS_CERTDIR=/github_repo/certs  # Set TLS_CERT_DIR to a subdirectory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the host Docker socket
      - ./dind-data:/var/lib/docker  # Persistent Docker data
      - .:/github_repo  # Mount the current directory
      - ./dind-post.sh:/post-install.sh  # Mount the post-install script
    ports:
      - "2376:2376"  # Expose Docker's secure TCP port
    command: >
      sh -c "
      TLS_CERT_DIR='/github_repo/certs';
      mkdir -p $TLS_CERT_DIR;
      if [ ! -f \"$TLS_CERT_DIR/ca.pem\" ] || [ ! -f \"$TLS_CERT_DIR/server-cert.pem\" ] || [ ! -f \"$TLS_CERT_DIR/server-key.pem\" ]; then
          echo '🔑 Generating self-signed TLS certificates...';
          openssl req -newkey rsa:4096 -nodes -keyout $TLS_CERT_DIR/server-key.pem -x509 -days 365 -out $TLS_CERT_DIR/server-cert.pem -subj '/CN=docker-in-docker';
          cp $TLS_CERT_DIR/server-cert.pem $TLS_CERT_DIR/ca.pem;
      fi;
      echo '🔒 Starting Docker daemon with TLS...';
      dockerd --debug --host=tcp://0.0.0.0:2376 --host=unix:///var/run/docker.sock --storage-driver=overlay2 --tlsverify --tlscacert=$TLS_CERT_DIR/ca.pem --tlscert=$TLS_CERT_DIR/server-cert.pem --tlskey=$TLS_CERT_DIR/server-key.pem &
      sleep 5 &&
      sh /post-install.sh"
volumes:
  dind-data: