version: '3.3'

services:
  docker-in-docker:
    image: docker:latest
    container_name: docker-in-docker
    privileged: true  # Required for Docker-in-Docker
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS for simplicity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the host Docker socket
      - ./dind-data:/var/lib/docker  # Persistent Docker data
      - ./:/dind
      - ./dind-post.sh:/post-install.sh  # Mount the post-install script

    ports:
      - "2375:2375"  # Expose Docker's TCP port for fallback
    command: >
      sh -c "dockerd --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock --storage-driver=overlay2 &
      sleep 5 &&
      sh /post-install.sh"

volumes:
  dind-data: