# This Docker Compose file sets up a firewall using Docker-in-Docker (DinD) and includes several useful containers.
# It includes NextDNS for DNS filtering, Pi-hole for ad-blocking, GitHub CLI for GitHub management,
# and a Debian container for various utilities. It also includes optional containers for Portainer
# (Docker management) and Watchtower (automatic updates).
# Define environment variables at the top
services:
  nextdns:
    image: nextdns/nextdns
    container_name: nextdns
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nextdns_config:/etc/nextdns
    cap_add:
      - NET_ADMIN
    command: run
    healthcheck:
      test: ["CMD", "nextdns", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: ${PIHOLE_TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - ./pihole_config:/etc/pihole
      - ./dnsmasq_config:/etc/dnsmasq.d
    healthcheck:
      test: ["CMD", "dig", "google.com", "@127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3

  github-cli:
    image: ghcr.io/cli/cli:latest
    container_name: github-cli
    restart: unless-stopped
    volumes:
      - ./github:/root/.config/gh
    entrypoint: /bin/sh

  utilities:
    image: debian:latest
    container_name: utilities
    restart: unless-stopped
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y curl wget nano git &&
      tail -f /dev/null
      "
    volumes:
      - ./utilities:/data

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9100:9000
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
