version: '3.3'

services:
  pihole:
    image: pihole/pihole:latest  # Use the latest compatible version
    container_name: pihole
    restart: unless-stopped
    ports:
      - "55:53/tcp"       # DNS TCP
      - "55:53/udp"       # DNS UDP
      - "90:80"           # Web interface
    environment:
      TZ: "America/Montreal"  # Set your timezone
      WEBPASSWORD: "p0tat0"  # Set a password for the web interface
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1

  nextdns:
    image: nextdns/nextdns:latest
    container_name: nextdns
    restart: unless-stopped
    network_mode: "host"  # Use host networking for DNS
    environment:
      - NEXTDNS_CONFIG=your-config-id  # Replace with your NextDNS configuration ID
      - LISTEN=127.0.0.1:53           # Listen on localhost port 53
      - REPORT_CLIENT_INFO=true       # Enable client info reporting
    command: >
      run
      --report-client-info
      --log-queries
      --cache-size=10MB

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9100:9000"  # Added quotes around the port mapping
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
